backend:
  name: git-gateway
  repo: lyonsbp/gridsome-snipcart

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'products'
    label: 'Products'
    folder: 'products'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Featured Image'
        name: 'image'
        widget: 'image'
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - label: 'Secondary Image'
        name: 'image'
        widget: 'image-1'
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - label: 'Secondary Image'
        name: 'image-2'
        widget: 'image'
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - label: 'Secondary Image'
        name: 'image-3'
        widget: 'image'
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - label: 'Secondary Image'
        name: 'image-4'
        widget: 'image'
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - label: 'Price'
        name: 'price'
        widget: 'number'
      - label: 'Sale (% Off)'
        name: 'sale'
        widget: 'number'
        default: '0'
        min: '0'
        max: '100'
        valueType: 'int'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'tags'
        name: 'tags'
        widget: 'list'
      - label: 'Quantity'
        name: 'quantity'
        widget: 'list'
        default: ['25', '50', '100', '250', '500', '1000']
      - label: 'Product Type'
        name: 'type'
        widget: 'select'
        options:
          - { label: 'Bag', value: 'bag' }
          - { label: 'Label', value: 'label' }
          - { label: 'Battery', value: 'battery' }
      - label: 'Weight (grams)'
        name: 'weight'
        widget: 'number'
        min: 0
        default: 1
