backend:
  name: github
  repo: lyonsbp/gridsome-snipcart

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'products'
    label: 'Products'
    folder: 'products'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Price', name: 'price', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'tags', name: 'tags', , widget: 'list' }
